server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,mappings
  endpoint:
    health:
      show-details: always


info:
  app:
    name: TechSuggestion Bot
    version: 0.0.1

perplexity:
  api:
    key: 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

app:
  ingestion:
    upload-dir: /Users/saurabhmadhure/uploads/products
    archive-dir: /Users/saurabhmadhure/uploads/archive



